services:
  backend:
    container_name: hackitall_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    
  db:
    image: mongo:latest
    container_name: hackitall_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data:
    driver: local

