services:
  frontend:
    container_name: hackitall_frontend
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

    networks:
      - hackitall_network
    
  backend:
    container_name: hackitall_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    
    networks:
      - hackitall_network
    
  db:
    image: mongo:latest
    container_name: hackitall_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    
    networks:
      - hackitall_network

networks:
  hackitall_network:
    name: hackitall_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

volumes:
  mongo_data:
    driver: local

